### ISSUE TITLE
Edit .html contents  

### ISSUE THREAD

**Issue by adedolapoadegboye** [adedolapoadegboye/adeResume#1]

**Comment by Pulkitxm** [comment]
Can I get assigned? lemme know how to start

**Comment by adedolapoadegboye** [comment]
> Can I get assigned? lemme know how to start

Hey thanks for dropping by at my page. I'm interested in collaborating in projects so if you maybe have an idea we can work on from A-Z, please let me know. As for this project, i'll assign a task to you once i have more things in my to-do list. Thanks once again.

**Comment by Pulkitxm** [comment]
yep we can do a collab. , tell me
